server:
    port: 8088

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shopapp
        username: root
        password: 12345678
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
api:
    prefix: api/v1

jwt:
    expiration: 2592000 # 30 days
    secretKey: UlyTpmrT+Phc/Nw8vEL+HBPIE3N9pBAKcJOfLHjFun8=
